/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package paneles;

/**
 *
 * @author juand
 */
public class CategoriaView extends javax.swing.JPanel {

    /**
     * Creates new form CategoriaView
     */
    public CategoriaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreCategoria3 = new javax.swing.JLabel();
        nombreCategoria = new javax.swing.JLabel();
        nombreCategoria2 = new javax.swing.JLabel();
        peli3 = new javax.swing.JLabel();
        peli1 = new javax.swing.JLabel();
        peli2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        nombreCategoria3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        nombreCategoria3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCategoria3.setText("jLabel1");

        nombreCategoria.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        nombreCategoria.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCategoria.setText("jLabel1");

        nombreCategoria2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        nombreCategoria2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nombreCategoria2.setText("jLabel1");

        peli3.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        peli3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        peli1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        peli1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        peli2.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        peli2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(peli1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(nombreCategoria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peli2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCategoria2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(peli3, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                    .addComponent(nombreCategoria3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombreCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peli3, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peli2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peli1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel nombreCategoria;
    public javax.swing.JLabel nombreCategoria2;
    public javax.swing.JLabel nombreCategoria3;
    public javax.swing.JLabel peli1;
    public javax.swing.JLabel peli2;
    public javax.swing.JLabel peli3;
    // End of variables declaration//GEN-END:variables
}
