
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import paneles.CategoriaView;

public class prinPelis extends javax.swing.JFrame {

    private CategoriaView panelPeliculasCategoria;
    int val = 0;

    public prinPelis() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Prestamo de peliculas | USER | GemeTech MusPeli");
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        this.panelPeliculasCategoria = new CategoriaView();
        this.panelPeliculasCategoria.nombreCategoria.setVisible(false);
        this.panelPeliculasCategoria.nombreCategoria2.setVisible(false);
        this.panelPeliculasCategoria.nombreCategoria3.setVisible(false);
        this.panelPeliculasCategoria.peli1.setVisible(false);
        this.panelPeliculasCategoria.peli2.setVisible(false);
        this.panelPeliculasCategoria.peli3.setVisible(false);
        this.jCategoria.setSelectedItem("General");
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(114, 114, 114)
                                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(this.panelPeliculasCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCategoria))
                                .addGap(8, 8, 8)
                                .addComponent(this.panelPeliculasCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl2 = new javax.swing.JLabel();
        label1 = new javax.swing.JLabel();
        jCategoria = new javax.swing.JComboBox<>();
        lbl12 = new javax.swing.JLabel();
        sinaliento = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        arruiname = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        matriarcado = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        belleza = new javax.swing.JLabel();
        halloween = new javax.swing.JLabel();
        lblPre1 = new javax.swing.JLabel();
        canciondeamor = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        hunted = new javax.swing.JLabel();
        med = new javax.swing.JLabel();
        apex = new javax.swing.JLabel();
        ex = new javax.swing.JLabel();
        fan = new javax.swing.JLabel();
        masalla = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        volver = new java.awt.Label();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt11 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        lbl24 = new javax.swing.JLabel();
        lblPre2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbl2.setText("CATEGORIA");

        label1.setFont(new java.awt.Font("Agency FB", 3, 36)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("PELICULAS GEMETECH");

        jCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Amor", "Terror", "Accion", "Comedia" }));
        jCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCategoriaActionPerformed(evt);
            }
        });

        lbl12.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl12.setText("SIN ALIENTO");

        sinaliento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sinalientoMouseClicked(evt);
            }
        });

        lbl13.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl13.setText("ARRUINAME");

        arruiname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arruinameMouseClicked(evt);
            }
        });

        lbl14.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl14.setText("MATRIARCADO");

        matriarcado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matriarcadoMouseClicked(evt);
            }
        });

        lbl15.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl15.setText("BELLEZA");

        belleza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bellezaMouseClicked(evt);
            }
        });

        halloween.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                halloweenMouseClicked(evt);
            }
        });

        lblPre1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblPre1.setText("Prestamos Restantes: ");

        canciondeamor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                canciondeamorMouseClicked(evt);
            }
        });

        lbl17.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl17.setText("CANCION DE AMOR");

        hunted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                huntedMouseClicked(evt);
            }
        });

        med.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                medMouseClicked(evt);
            }
        });

        apex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                apexMouseClicked(evt);
            }
        });

        ex.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exMouseClicked(evt);
            }
        });

        fan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fanMouseClicked(evt);
            }
        });

        masalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                masallaMouseClicked(evt);
            }
        });

        lbl18.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl18.setText("MAS ALLA");

        lbl19.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl19.setText("MEJOR FAN");

        lbl20.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl20.setText("NOCHE SEX");

        lbl21.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl21.setText("APEX");

        lbl22.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl22.setText("MEDIEVAL");

        lbl23.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl23.setText("HUNTED");

        volver.setBackground(new java.awt.Color(255, 255, 255));
        volver.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        volver.setText("Volver");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });

        bt1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt1.setText("ALQUILAR");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt2.setText("ALQUILAR");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt3.setText("ALQUILAR");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt4.setText("ALQUILAR");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt5.setText("ALQUILAR");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt6.setText("ALQUILAR");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt12.setText("ALQUILAR");
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt12ActionPerformed(evt);
            }
        });

        bt11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt11.setText("ALQUILAR");
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt11ActionPerformed(evt);
            }
        });

        bt10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt10.setText("ALQUILAR");
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt10ActionPerformed(evt);
            }
        });

        bt9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt9.setText("ALQUILAR");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt8.setText("ALQUILAR");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt7.setText("ALQUILAR");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        lbl24.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl24.setText("HALLOWEEN");

        lblPre2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblPre2.setForeground(new java.awt.Color(0, 0, 255));
        lblPre2.setText("3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lbl12)
                    .addComponent(sinaliento, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt1)
                    .addComponent(lbl18)
                    .addComponent(masalla, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ex, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arruiname, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lbl13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(matriarcado, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(belleza, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(fan, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(apex, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(lbl14)
                                .addGap(70, 70, 70)
                                .addComponent(lbl15))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl20)
                            .addComponent(bt2)
                            .addComponent(bt12))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bt3)
                                    .addComponent(lbl19))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addComponent(lbl21))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(bt4))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(bt10)
                                .addGap(71, 71, 71)
                                .addComponent(bt9)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl22)
                                .addGap(99, 99, 99)
                                .addComponent(lbl23))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bt5)
                                .addGap(87, 87, 87)
                                .addComponent(bt6))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(bt11)
                        .addGap(96, 96, 96)
                        .addComponent(bt8))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(halloween, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(med, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(canciondeamor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hunted, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl24)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(lbl17))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPre1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblPre2)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(lblPre1)
                    .addComponent(lblPre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCategoria))
                        .addGap(82, 82, 82)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sinaliento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(arruiname, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(matriarcado, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(canciondeamor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl24)
                            .addComponent(lbl15)
                            .addComponent(lbl14)
                            .addComponent(lbl13)
                            .addComponent(lbl12)
                            .addComponent(lbl17))
                        .addGap(27, 27, 27)
                        .addComponent(belleza, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(halloween, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bt2)
                                .addComponent(bt3)
                                .addComponent(bt4)
                                .addComponent(bt5)
                                .addComponent(bt6)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl20)
                                    .addComponent(lbl18)
                                    .addComponent(lbl19))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl22))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl23))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbl21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ex, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(masalla, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(hunted, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(med, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apex, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bt7)
                                .addComponent(bt9)
                                .addComponent(bt10))
                            .addComponent(bt12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bt11)
                                .addComponent(bt8)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        volver.getAccessibleContext().setAccessibleName("volver");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCategoriaActionPerformed
        String opcion = jCategoria.getSelectedItem().toString();
        switch (opcion) {
            case "General":

                actLbl();
                this.panelPeliculasCategoria.nombreCategoria.setVisible(false);
                this.panelPeliculasCategoria.nombreCategoria2.setVisible(false);
                this.panelPeliculasCategoria.nombreCategoria3.setVisible(false);
                this.panelPeliculasCategoria.peli1.setVisible(false);
                this.panelPeliculasCategoria.peli2.setVisible(false);
                this.panelPeliculasCategoria.peli3.setVisible(false);
                this.panelPeliculasCategoria.setBackground(new Color(255, 255, 255));
                break;
            case "Terror":
                desLbl();
                this.panelPeliculasCategoria.nombreCategoria.setVisible(true);
                this.panelPeliculasCategoria.nombreCategoria2.setVisible(true);
                this.panelPeliculasCategoria.nombreCategoria3.setVisible(true);
                this.panelPeliculasCategoria.peli1.setVisible(true);
                this.panelPeliculasCategoria.peli2.setVisible(true);
                this.panelPeliculasCategoria.peli3.setVisible(true);
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli1, "src/hunted.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli2, "src/matriarcado.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli3, "src/halloween.jpg");
                this.panelPeliculasCategoria.nombreCategoria.setText("HUNTED");
                this.panelPeliculasCategoria.nombreCategoria2.setText("MATRIARCADO");
                this.panelPeliculasCategoria.nombreCategoria3.setText("HALLOWEEN");
                this.panelPeliculasCategoria.setBackground(new Color(255, 255, 255));
                break;
            case "Accion":
                desLbl();
                this.panelPeliculasCategoria.nombreCategoria.setVisible(true);
                this.panelPeliculasCategoria.nombreCategoria2.setVisible(true);
                this.panelPeliculasCategoria.nombreCategoria3.setVisible(true);
                this.panelPeliculasCategoria.peli1.setVisible(true);
                this.panelPeliculasCategoria.peli2.setVisible(true);
                this.panelPeliculasCategoria.peli3.setVisible(true);
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli1, "src/arruiname.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli2, "src/apex.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli3, "src/med.jpg");
                this.panelPeliculasCategoria.nombreCategoria.setText("ARRUINAME");
                this.panelPeliculasCategoria.nombreCategoria2.setText("APEX");
                this.panelPeliculasCategoria.nombreCategoria3.setText("MEDIEVAL");
                this.panelPeliculasCategoria.setBackground(new Color(255, 255, 255));
                break;
            case "Amor":
                desLbl();
                this.panelPeliculasCategoria.nombreCategoria.setVisible(true);
                this.panelPeliculasCategoria.nombreCategoria2.setVisible(true);
                this.panelPeliculasCategoria.nombreCategoria3.setVisible(true);
                this.panelPeliculasCategoria.peli1.setVisible(true);
                this.panelPeliculasCategoria.peli2.setVisible(true);
                this.panelPeliculasCategoria.peli3.setVisible(true);
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli1, "src/canciondeamor.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli2, "src/belleza.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli3, "src/masalla.jpg");
                this.panelPeliculasCategoria.nombreCategoria.setText("CANCION DE AMOR");
                this.panelPeliculasCategoria.nombreCategoria2.setText("BELLEZA");
                this.panelPeliculasCategoria.nombreCategoria3.setText("MAS ALLA");
                this.panelPeliculasCategoria.setBackground(new Color(255, 255, 255));
                break;
            case "Comedia":
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli1, "src/sinaliento.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli2, "src/mejorfan.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli3, "src/nochesex.jpg");
                this.panelPeliculasCategoria.nombreCategoria.setText("SIN ALIENTO");
                this.panelPeliculasCategoria.nombreCategoria2.setText("TU MEJOR FAN");
                this.panelPeliculasCategoria.nombreCategoria3.setText("NOCHE DE SEXO");
                this.panelPeliculasCategoria.setBackground(new Color(255, 255, 255));
                break;
            default:
                break;
        }


    }//GEN-LAST:event_jCategoriaActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        inUserAl iu = new inUserAl();
        iu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        val = 1;
        Prestamos();
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        val = 2;
        Prestamos();
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        val = 3;
        Prestamos();
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        val = 4;
        Prestamos();
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        val = 5;
        Prestamos();
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        val = 6;
        Prestamos();
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        val = 7;
        Prestamos();
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        val = 8;
        Prestamos();
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        val = 9;
        Prestamos();
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt10ActionPerformed
        val = 10;
        Prestamos();
    }//GEN-LAST:event_bt10ActionPerformed

    private void bt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt11ActionPerformed
        val = 11;
        Prestamos();
    }//GEN-LAST:event_bt11ActionPerformed

    private void bt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt12ActionPerformed
        val = 12;
        Prestamos();
    }//GEN-LAST:event_bt12ActionPerformed

    private void halloweenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_halloweenMouseClicked
        peli1 peli1=new peli1();
        peli1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_halloweenMouseClicked

    private void sinalientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinalientoMouseClicked
      peli2 llamado=new peli2();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sinalientoMouseClicked

    private void arruinameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arruinameMouseClicked
       peli3 llamado=new peli3();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_arruinameMouseClicked

    private void matriarcadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matriarcadoMouseClicked
        peli4 llamado=new peli4();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_matriarcadoMouseClicked

    private void bellezaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bellezaMouseClicked
        peli5 llamado=new peli5();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bellezaMouseClicked

    private void canciondeamorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_canciondeamorMouseClicked
        peli6 llamado=new peli6();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_canciondeamorMouseClicked

    private void masallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masallaMouseClicked
        peli7 llamado=new peli7();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_masallaMouseClicked

    private void exMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exMouseClicked
      peli8 llamado=new peli8();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_exMouseClicked

    private void fanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fanMouseClicked
        peli9 llamado=new peli9();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_fanMouseClicked

    private void apexMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_apexMouseClicked
         peli10 llamado=new peli10();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_apexMouseClicked

    private void medMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_medMouseClicked
        peli11 llamado=new peli11();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_medMouseClicked

    private void huntedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_huntedMouseClicked
         peli12 llamado=new peli12();
        llamado.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_huntedMouseClicked

    /**
     */
    public void desLbl() {
        lbl12.setVisible(false);
        lbl13.setVisible(false);
        lbl14.setVisible(false);
        lbl15.setVisible(false);
        lbl24.setVisible(false);
        lblPre1.setVisible(false);
        lbl17.setVisible(false);
        lbl18.setVisible(false);
        lbl19.setVisible(false);
        lbl20.setVisible(false);
        lbl21.setVisible(false);
        lbl22.setVisible(false);
        lbl23.setVisible(false);
        bt1.setVisible(false);
        bt2.setVisible(false);
        bt3.setVisible(false);
        bt4.setVisible(false);
        bt5.setVisible(false);
        bt6.setVisible(false);
        bt7.setVisible(false);
        bt8.setVisible(false);
        bt9.setVisible(false);
        bt10.setVisible(false);
        bt11.setVisible(false);
        bt12.setVisible(false);
        lblPre1.setVisible(false);
        lblPre2.setVisible(false);
        arruiname.setVisible(false);
        matriarcado.setVisible(false);
        belleza.setVisible(false);
        halloween.setVisible(false);
        canciondeamor.setVisible(false);
        sinaliento.setVisible(false);
        masalla.setVisible(false);
        fan.setVisible(false);
        ex.setVisible(false);
        apex.setVisible(false);
        med.setVisible(false);
        hunted.setVisible(false);
    }

    public void actLbl() {
        rsscalelabel.RSScaleLabel.setScaleLabel(arruiname, "src/arruiname.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(matriarcado, "src/matriarcado.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(belleza, "src/belleza.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(halloween, "src/halloween.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(canciondeamor, "src/canciondeamor.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(sinaliento, "src/sinaliento.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(masalla, "src/masalla.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(fan, "src/mejorfan.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(ex, "src/nochesex.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(apex, "src/apex.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(med, "src/med.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(hunted, "src/hunted.jpg");
        lbl12.setVisible(true);
        lbl13.setVisible(true);
        lbl14.setVisible(true);
        lbl15.setVisible(true);
        lbl24.setVisible(true);
        lblPre1.setVisible(true);
        lbl17.setVisible(true);
        lbl18.setVisible(true);
        lbl19.setVisible(true);
        lbl20.setVisible(true);
        lbl21.setVisible(true);
        lbl22.setVisible(true);
        lbl23.setVisible(true);
        bt1.setVisible(true);
        bt2.setVisible(true);
        bt3.setVisible(true);
        bt4.setVisible(true);
        bt5.setVisible(true);
        bt6.setVisible(true);
        bt7.setVisible(true);
        bt8.setVisible(true);
        bt9.setVisible(true);
        bt10.setVisible(true);
        bt11.setVisible(true);
        bt12.setVisible(true);
        lblPre1.setVisible(true);
        lblPre2.setVisible(true);
        arruiname.setVisible(true);
        matriarcado.setVisible(true);
        belleza.setVisible(true);
        halloween.setVisible(true);
        canciondeamor.setVisible(true);
        sinaliento.setVisible(true);
        masalla.setVisible(true);
        fan.setVisible(true);
        ex.setVisible(true);
        apex.setVisible(true);
        med.setVisible(true);
        hunted.setVisible(true);
    }

    public void resetLbl() {
        lbl12.setVisible(true);
        lbl13.setText("");
        lbl14.setText("");
        lbl15.setText("");
        lblPre1.setText("");
        lbl17.setText("");
        lbl18.setText("");
        lbl19.setText("");
        lbl20.setText("");
        lbl21.setText("");
        lbl22.setText("");
        lbl23.setText("");
        arruiname.setText("");
        matriarcado.setText("");
        belleza.setText("");
        halloween.setText("");
        canciondeamor.setText("");
        sinaliento.setText("");
        masalla.setText("");
        fan.setText("");
        ex.setText("");
        apex.setText("");
        med.setText("");
        hunted.setText("");

    }
    int contador = 0;
    LocalDate todaysDate = LocalDate.now();
    LocalDate todaysDate2 = todaysDate.plusDays(3);
    int multUni = 10000, dayActu, dayLimit;
     public static ArrayList<String> fechaPres = new ArrayList<>();

    public void fechaPre() {
        dayActu = todaysDate.getDayOfMonth();
        dayLimit = todaysDate2.getDayOfMonth();
        JOptionPane.showMessageDialog(this, "Fecha Actual: " + todaysDate + "\n Fecha de Entrega: " + todaysDate2);
        fechaPres.add(Integer.toString(dayLimit));/// TRAE EL DIA LIMITE
        System.out.println(fechaPres);
    }
    public static ArrayList<String> peliPres = new ArrayList<>();
    public static ArrayList<String> prestamos23= new ArrayList<>();
   

    public void valBoton() {
        switch (val) {
            case 1:
                peliPres.add(lbl12.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + lbl12.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 2:
                peliPres.add(lbl13.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl13.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 3:
                peliPres.add(lbl14.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl14.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 4:
                peliPres.add(lbl15.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl15.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 5:
                peliPres.add(lbl15.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl24.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 6:
                peliPres.add(lbl17.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl17.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 7:
                peliPres.add(lbl18.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl18.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 8:
                peliPres.add(lbl19.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl19.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 9:
                peliPres.add(lbl20.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl20.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 10:
                peliPres.add(lbl21.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl21.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 11:
                peliPres.add(lbl22.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl22.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 12:
                peliPres.add(lbl23.getText());
                System.out.println(peliPres);
                JOptionPane.showMessageDialog(rootPane, "Has prestado la pelicula" + " " + lbl23.getText(), "PRESTAMO CON EXITO", 1);
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "TECH: !Ops¡ No reconoci el boton", "ERROR 404 NOT FOUND", 0);
                break;
        }

    }

    public void Prestamos() {
        contador++;
        lblPre2.setText(Integer.toString(3 - contador));
        switch (contador) {
            case 0:
                JOptionPane.showMessageDialog(rootPane, "No puedes prestar mas peliculas", "Error 404 NOT FOUND", 0);
                break;
            case 1:
                for (int i = 0; i < 1; i++) {
                    valBoton();
                }
                fechaPre();
                break;
            case 2:
                for (int i = 0 + 1; i < 2; i++) {
                    valBoton();
                }
                fechaPre();
                break;
            case 3:
                for (int i = 0 + 1 + 1; i < 2 + 1; i++) {
                    valBoton();
                }
                fechaPre();
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "No puedes prestar mas peliculas", "Error 404 NOT FOUND", 0);
                lblPre2.setText(Integer.toString(0));
                break;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prinPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prinPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prinPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prinPelis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prinPelis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apex;
    private javax.swing.JLabel arruiname;
    private javax.swing.JLabel belleza;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JLabel canciondeamor;
    private javax.swing.JLabel ex;
    private javax.swing.JLabel fan;
    private javax.swing.JLabel halloween;
    private javax.swing.JLabel hunted;
    private javax.swing.JComboBox<String> jCategoria;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lblPre1;
    private javax.swing.JLabel lblPre2;
    private javax.swing.JLabel masalla;
    private javax.swing.JLabel matriarcado;
    private javax.swing.JLabel med;
    private javax.swing.JLabel sinaliento;
    private java.awt.Label volver;
    // End of variables declaration//GEN-END:variables
}
