
import java.awt.Color;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.GroupLayout;
import javax.swing.JOptionPane;
import paneles.CategoriaView;

public class prinMusi extends javax.swing.JFrame {

    private CategoriaView panelPeliculasCategoria;
    int val = 0;

    public prinMusi() {
        initComponents();
        this.setTitle("Prestamos de musica | USER | GemeTech MusPeli");
        this.getContentPane().setBackground(Color.white);
        this.setLocationRelativeTo(null);
        this.panelPeliculasCategoria = new CategoriaView();
        this.panelPeliculasCategoria.nombreCategoria.setVisible(false);
        this.panelPeliculasCategoria.nombreCategoria2.setVisible(false);
        this.panelPeliculasCategoria.nombreCategoria3.setVisible(false);
        this.panelPeliculasCategoria.peli1.setVisible(false);
        this.panelPeliculasCategoria.peli2.setVisible(false);
        this.panelPeliculasCategoria.peli3.setVisible(false);
        this.jCategoria.setSelectedItem("General");
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(114, 114, 114)
                                                .addComponent(lbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addComponent(this.panelPeliculasCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(label1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCategoria))
                                .addGap(8, 8, 8)
                                .addComponent(this.panelPeliculasCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(15, Short.MAX_VALUE))
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        jCategoria = new javax.swing.JComboBox<>();
        lbl12 = new javax.swing.JLabel();
        gasolina = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        newRules = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        nirvana = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        breakHeart = new javax.swing.JLabel();
        inClub = new javax.swing.JLabel();
        lblPre1 = new javax.swing.JLabel();
        thunder = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        goodDay = new javax.swing.JLabel();
        forgotAbout = new javax.swing.JLabel();
        basketCase = new javax.swing.JLabel();
        darkHorse = new javax.swing.JLabel();
        sexyMovimiento = new javax.swing.JLabel();
        nocheSexo = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        volver = new java.awt.Label();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt12 = new javax.swing.JButton();
        bt11 = new javax.swing.JButton();
        bt10 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        lbl24 = new javax.swing.JLabel();
        lblPre2 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Agency FB", 3, 36)); // NOI18N
        label1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label1.setText("MUSICA GEMETECH");

        jCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General", "Reggaeton", "Pop", "Rock", "HipHop" }));
        jCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCategoriaActionPerformed(evt);
            }
        });

        lbl12.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl12.setText("Gasolina");

        lbl13.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl13.setText(" New Rules");

        lbl14.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl14.setText("Smells Like");

        lbl15.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl15.setText("Break My Heart");

        lblPre1.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblPre1.setText("Prestamos Restantes: ");

        lbl17.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl17.setText("Thunderstruck");

        lbl18.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl18.setText("Noche De Sexo");

        lbl19.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl19.setText("Sexy Movimiento");

        lbl20.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl20.setText("Dark Horse");

        lbl21.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl21.setText("Basket Case");

        lbl22.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl22.setText("Forgot About");

        lbl23.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl23.setText("It Was A Good");

        volver.setBackground(new java.awt.Color(255, 255, 255));
        volver.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        volver.setText("Volver");
        volver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volverMouseClicked(evt);
            }
        });

        bt1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt1.setText("ALQUILAR");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt2.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt2.setText("ALQUILAR");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        bt3.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt3.setText("ALQUILAR");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        bt4.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt4.setText("ALQUILAR");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt5.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt5.setText("ALQUILAR");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt6.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt6.setText("ALQUILAR");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt12.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt12.setText("ALQUILAR");
        bt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt12ActionPerformed(evt);
            }
        });

        bt11.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt11.setText("ALQUILAR");
        bt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt11ActionPerformed(evt);
            }
        });

        bt10.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt10.setText("ALQUILAR");
        bt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt10ActionPerformed(evt);
            }
        });

        bt9.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt9.setText("ALQUILAR");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt8.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt8.setText("ALQUILAR");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt7.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        bt7.setText("ALQUILAR");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        lbl24.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lbl24.setText("50 Cent");

        lblPre2.setFont(new java.awt.Font("Agency FB", 0, 24)); // NOI18N
        lblPre2.setForeground(new java.awt.Color(0, 0, 255));
        lblPre2.setText("3");

        lbl2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl2.setText("CATEGORIA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl20))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(lbl2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(lbl12)
                                    .addComponent(gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt1)
                                    .addComponent(bt7)
                                    .addComponent(nocheSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(newRules, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addComponent(lbl13))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(bt2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(darkHorse, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addComponent(bt9)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(sexyMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(basketCase, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl19)
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(bt4)
                                            .addComponent(lbl21))
                                        .addGap(24, 24, 24)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(forgotAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                        .addComponent(goodDay, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(bt12)
                                        .addComponent(bt6))
                                    .addComponent(lbl23)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl14)
                                            .addComponent(bt3)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(nirvana, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(bt8)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl15)
                                            .addComponent(breakHeart, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addComponent(bt10)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(39, 39, 39)
                                        .addComponent(bt11)
                                        .addGap(48, 48, 48))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(inClub, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lbl22)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(bt5)
                                                        .addGroup(layout.createSequentialGroup()
                                                            .addGap(4, 4, 4)
                                                            .addComponent(lbl24))))))
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(thunder, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lbl17)
                                                .addGap(9, 9, 9))))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblPre1)))
                .addComponent(lblPre2)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label1)
                    .addComponent(lblPre1)
                    .addComponent(lblPre2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl14)
                                    .addComponent(lbl15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl12)
                                .addComponent(lbl13)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gasolina, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nirvana, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(breakHeart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newRules, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inClub, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(thunder, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bt2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bt1)
                        .addComponent(bt3)
                        .addComponent(bt4)
                        .addComponent(bt5)
                        .addComponent(bt6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sexyMovimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl22, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl23))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(forgotAbout, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(goodDay, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt12)
                            .addComponent(bt8)
                            .addComponent(bt10)
                            .addComponent(bt11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl21, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lbl18)
                                .addComponent(lbl20)
                                .addComponent(lbl19)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nocheSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(darkHorse, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(basketCase, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bt9)
                            .addComponent(bt7))
                        .addGap(10, 10, 10)))
                .addComponent(volver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        volver.getAccessibleContext().setAccessibleName("volver");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCategoriaActionPerformed
        String opcion = jCategoria.getSelectedItem().toString();
        switch (opcion) {
            case "General":

                actLbl();
                this.panelPeliculasCategoria.nombreCategoria.setVisible(false);
                this.panelPeliculasCategoria.nombreCategoria2.setVisible(false);
                this.panelPeliculasCategoria.nombreCategoria3.setVisible(false);
                this.panelPeliculasCategoria.peli1.setVisible(false);
                this.panelPeliculasCategoria.peli2.setVisible(false);
                this.panelPeliculasCategoria.peli3.setVisible(false);
                this.panelPeliculasCategoria.setBackground(new Color(255, 255, 255));
                break;
            case "Reggaeton":
                desLbl();
                this.panelPeliculasCategoria.nombreCategoria.setVisible(true);
                this.panelPeliculasCategoria.nombreCategoria2.setVisible(true);
                this.panelPeliculasCategoria.nombreCategoria3.setVisible(true);
                this.panelPeliculasCategoria.peli1.setVisible(true);
                this.panelPeliculasCategoria.peli2.setVisible(true);
                this.panelPeliculasCategoria.peli3.setVisible(true);
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli1, "src/Gasolina.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli2, "src/NocheSexo.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli3, "src/SexyMovimiento.jpg");
                this.panelPeliculasCategoria.nombreCategoria.setText("Gasolina");
                this.panelPeliculasCategoria.nombreCategoria2.setText("Noche De Sexo");
                this.panelPeliculasCategoria.nombreCategoria3.setText("Sexy Movimiento");
                this.panelPeliculasCategoria.setBackground(new Color(255, 255, 255));
                break;
            case "Pop":
                desLbl();
                this.panelPeliculasCategoria.nombreCategoria.setVisible(true);
                this.panelPeliculasCategoria.nombreCategoria2.setVisible(true);
                this.panelPeliculasCategoria.nombreCategoria3.setVisible(true);
                this.panelPeliculasCategoria.peli1.setVisible(true);
                this.panelPeliculasCategoria.peli2.setVisible(true);
                this.panelPeliculasCategoria.peli3.setVisible(true);
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli1, "src/BreakHeart.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli2, "src/DarkHorse.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli3, "src/NewRules.jpg");
                this.panelPeliculasCategoria.nombreCategoria.setText("New Rules");
                this.panelPeliculasCategoria.nombreCategoria2.setText("Dark Horse");
                this.panelPeliculasCategoria.nombreCategoria3.setText("Basket Case");
                this.panelPeliculasCategoria.setBackground(new Color(255, 255, 255));
                break;
            case "Rock":
                desLbl();
                panelPeliculasCategoria.nombreCategoria.setVisible(true);
                panelPeliculasCategoria.nombreCategoria2.setVisible(true);
                panelPeliculasCategoria.nombreCategoria3.setVisible(true);
                panelPeliculasCategoria.peli1.setVisible(true);
                panelPeliculasCategoria.peli2.setVisible(true);
                panelPeliculasCategoria.peli3.setVisible(true);
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli1, "src/TeenSpirit.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli2, "src/BasketCase.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli3, "src/ThunderStruck.jpg");
                panelPeliculasCategoria.nombreCategoria.setText("Smeel - Nirvana");
                panelPeliculasCategoria.nombreCategoria2.setText("Basket case");
                panelPeliculasCategoria.nombreCategoria3.setText("ThunderStruck");
                panelPeliculasCategoria.setBackground(new Color(255, 255, 255));
                break;
            case "HipHop":
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli1, "src/WasGoodDay.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli2, "src/InDaClub.jpg");
                rsscalelabel.RSScaleLabel.setScaleLabel(panelPeliculasCategoria.peli3, "src/ForgotAbout.jpg");
                this.panelPeliculasCategoria.nombreCategoria.setText("Ice Cube");
                this.panelPeliculasCategoria.nombreCategoria2.setText("50 Cent");
                this.panelPeliculasCategoria.nombreCategoria3.setText("Forgot About Dre");
                this.panelPeliculasCategoria.setBackground(new Color(255, 255, 255));
                break;
            default:
                break;
        }


    }//GEN-LAST:event_jCategoriaActionPerformed

    private void volverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volverMouseClicked
        inUserAl iu = new inUserAl();
        iu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverMouseClicked

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        val = 1;
        Prestamos();
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        val = 2;
        Prestamos();
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        val = 3;
        Prestamos();
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        val = 4;
        Prestamos();
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        val = 5;
        Prestamos();
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        val = 6;
        Prestamos();
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        val = 7;
        Prestamos();
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        val = 8;
        Prestamos();
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        val = 9;
        Prestamos();
    }//GEN-LAST:event_bt9ActionPerformed

    private void bt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt10ActionPerformed
        val = 10;
        Prestamos();
    }//GEN-LAST:event_bt10ActionPerformed

    private void bt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt11ActionPerformed
        val = 11;
        Prestamos();
    }//GEN-LAST:event_bt11ActionPerformed

    private void bt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt12ActionPerformed
        val = 12;
        Prestamos();
    }//GEN-LAST:event_bt12ActionPerformed

    /**
     */
    public void desLbl() {
        lbl12.setVisible(false);
        lbl13.setVisible(false);
        lbl14.setVisible(false);
        lbl15.setVisible(false);
        lbl24.setVisible(false);
        lblPre1.setVisible(false);
        lbl17.setVisible(false);
        lbl18.setVisible(false);
        lbl19.setVisible(false);
        lbl20.setVisible(false);
        lbl21.setVisible(false);
        lbl22.setVisible(false);
        lbl23.setVisible(false);
        bt1.setVisible(false);
        bt2.setVisible(false);
        bt3.setVisible(false);
        bt4.setVisible(false);
        bt5.setVisible(false);
        bt6.setVisible(false);
        bt7.setVisible(false);
        bt8.setVisible(false);
        bt9.setVisible(false);
        bt10.setVisible(false);
        bt11.setVisible(false);
        bt12.setVisible(false);
        lblPre1.setVisible(false);
        lblPre2.setVisible(false);
        newRules.setVisible(false);
        nirvana.setVisible(false);
        breakHeart.setVisible(false);
        inClub.setVisible(false);
        thunder.setVisible(false);
        gasolina.setVisible(false);
        nocheSexo.setVisible(false);
        sexyMovimiento.setVisible(false);
        darkHorse.setVisible(false);
        basketCase.setVisible(false);
        forgotAbout.setVisible(false);
        goodDay.setVisible(false);
    }

    public void actLbl() {
        rsscalelabel.RSScaleLabel.setScaleLabel(basketCase, "src/BasketCase.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(breakHeart, "src/BreakHeart.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(darkHorse, "src/DarkHorse.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(forgotAbout, "src/ForgotAbout.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(gasolina, "src/Gasolina.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(inClub, "src/InDaClub.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(newRules, "src/NewRules.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(nocheSexo, "src/NocheSexo.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(sexyMovimiento, "src/SexyMovimiento.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(nirvana, "src/TeenSpirit.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(thunder, "src/ThunderStruck.jpg");
        rsscalelabel.RSScaleLabel.setScaleLabel(goodDay, "src/WasGoodDay.jpg");
        lbl12.setVisible(true);
        lbl13.setVisible(true);
        lbl14.setVisible(true);
        lbl15.setVisible(true);
        lbl24.setVisible(true);
        lblPre1.setVisible(true);
        lbl17.setVisible(true);
        lbl18.setVisible(true);
        lbl19.setVisible(true);
        lbl20.setVisible(true);
        lbl21.setVisible(true);
        lbl22.setVisible(true);
        lbl23.setVisible(true);
        bt1.setVisible(true);
        bt2.setVisible(true);
        bt3.setVisible(true);
        bt4.setVisible(true);
        bt5.setVisible(true);
        bt6.setVisible(true);
        bt7.setVisible(true);
        bt8.setVisible(true);
        bt9.setVisible(true);
        bt10.setVisible(true);
        bt11.setVisible(true);
        bt12.setVisible(true);
        lblPre1.setVisible(true);
        lblPre2.setVisible(true);
        newRules.setVisible(true);
        nirvana.setVisible(true);
        breakHeart.setVisible(true);
        inClub.setVisible(true);
        thunder.setVisible(true);
        gasolina.setVisible(true);
        nocheSexo.setVisible(true);
        sexyMovimiento.setVisible(true);
        darkHorse.setVisible(true);
        basketCase.setVisible(true);
        forgotAbout.setVisible(true);
        goodDay.setVisible(true);
    }

    public void resetLbl() {
        lbl12.setVisible(true);
        lbl13.setText("");
        lbl14.setText("");
        lbl15.setText("");
        lblPre1.setText("");
        lbl17.setText("");
        lbl18.setText("");
        lbl19.setText("");
        lbl20.setText("");
        lbl21.setText("");
        lbl22.setText("");
        lbl23.setText("");
        newRules.setText("");
        nirvana.setText("");
        breakHeart.setText("");
        inClub.setText("");
        thunder.setText("");
        gasolina.setText("");
        nocheSexo.setText("");
        sexyMovimiento.setText("");
        darkHorse.setText("");
        basketCase.setText("");
        forgotAbout.setText("");
        goodDay.setText("");

    }
    int contador = 0;
    LocalDate todaysDate = LocalDate.now();
    LocalDate todaysDate2 = todaysDate.plusDays(3);
    int multUni = 10000, dayActu, dayLimit;
     public static ArrayList<String> fechaPreM = new ArrayList<>();

    public void fechaPre() {
        dayActu = todaysDate.getDayOfMonth();
        dayLimit = todaysDate2.getDayOfMonth();
        JOptionPane.showMessageDialog(this, "Fecha Actual: " + todaysDate + "\n Fecha de Entrega: " + todaysDate2);
        /*fechaPreM.add(Integer.toString(dayLimit));/// TRAE EL DIA LIMITE*/
        prinPelis.fechaPres.add(Integer.toString(dayLimit));
    }
    public static ArrayList<String> musiPres = new ArrayList<>();

    public void valBoton() {
        switch (val) {
            case 1:
                /*musiPres.add(lbl12.getText());*/
                prinPelis.peliPres.add(lbl12.getText());
                /*System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + lbl12.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 2:
                /*musiPres.add(lbl13.getText());*/
                prinPelis.peliPres.add(lbl13.getText());
               /* System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl13.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 3:
                /*musiPres.add(lbl14.getText());*/
                prinPelis.peliPres.add(lbl14.getText());
               /* System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl14.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 4:
               /* musiPres.add(lbl15.getText());*/
                prinPelis.peliPres.add(lbl15.getText());
                /*System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl15.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 5:
                /*musiPres.add(lbl24.getText());*/
                prinPelis.peliPres.add(lbl24.getText());
               /* System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl24.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 6:
               /* musiPres.add(lbl17.getText());*/
                prinPelis.peliPres.add(lbl17.getText());
               /* System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl17.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 7:
               /* musiPres.add(lbl18.getText());*/
                prinPelis.peliPres.add(lbl18.getText());
               /* System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl18.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 8:
                /*musiPres.add(lbl19.getText());*/
                prinPelis.peliPres.add(lbl19.getText());
                /*System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl19.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 9:
                /*musiPres.add(lbl20.getText());*/
                prinPelis.peliPres.add(lbl20.getText());
               /* System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl20.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 10:
                /*musiPres.add(lbl21.getText());*/
                prinPelis.peliPres.add(lbl21.getText());
                /*System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl21.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 11:
                /*musiPres.add(lbl22.getText());*/
                prinPelis.peliPres.add(lbl22.getText());
              /*  System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl22.getText(), "PRESTAMO CON EXITO", 1);
                break;
            case 12:
               /* musiPres.add(lbl23.getText());*/
                prinPelis.peliPres.add(lbl23.getText());
                /*System.out.println(musiPres);*/
                JOptionPane.showMessageDialog(rootPane, "Has prestado la musica" + " " + lbl23.getText(), "PRESTAMO CON EXITO", 1);
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "TECH: !Ops¡ No reconoci el boton", "ERROR 404 NOT FOUND", 0);
                break;
        }

    }

    public void Prestamos() {
        contador++;
        lblPre2.setText(Integer.toString(3 - contador));
        switch (contador) {
            case 0:
                JOptionPane.showMessageDialog(rootPane, "No puedes prestar mas musica", "Error 404 NOT FOUND", 0);
                break;
            case 1:
                for (int i = 0; i < 1; i++) {
                    valBoton();
                }
                fechaPre();
                break;
            case 2:
                for (int i = 0 + 1; i < 2; i++) {
                    valBoton();
                }
                fechaPre();
                break;
            case 3:
                for (int i = 0 + 1 + 1; i < 2 + 1; i++) {
                    valBoton();
                }
                fechaPre();
                break;
            default:
                JOptionPane.showMessageDialog(rootPane, "No puedes prestar mas musica", "Error 404 NOT FOUND", 0);
                lblPre2.setText(Integer.toString(0));
                break;
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(prinMusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(prinMusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(prinMusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(prinMusi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new prinMusi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basketCase;
    private javax.swing.JLabel breakHeart;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt10;
    private javax.swing.JButton bt11;
    private javax.swing.JButton bt12;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JLabel darkHorse;
    private javax.swing.JLabel forgotAbout;
    private javax.swing.JLabel gasolina;
    private javax.swing.JLabel goodDay;
    private javax.swing.JLabel inClub;
    private javax.swing.JComboBox<String> jCategoria;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lblPre1;
    private javax.swing.JLabel lblPre2;
    private javax.swing.JLabel newRules;
    private javax.swing.JLabel nirvana;
    private javax.swing.JLabel nocheSexo;
    private javax.swing.JLabel sexyMovimiento;
    private javax.swing.JLabel thunder;
    private java.awt.Label volver;
    // End of variables declaration//GEN-END:variables
}
